import { BlogPost } from './blog-posts'

export const FOREIGNERS_BLOG_POSTS: BlogPost[] = [
  {
    id: 'fop-dla-ukraincow',
    title: 'Jak Założyć ФОП w Polsce - Przewodnik dla Ukraińców 2026',
    slug: 'fop-dla-ukraincow',
    excerpt: 'Krok po kroku instrukcja zakładania ФОП (firmy) w Polsce dla Ukraińców. Dokumenty, proces, koszty i wszystko co musisz wiedzieć.',
    category: 'Dla obcokrajowców',
    readTime: '10 min',
    date: '2026-03-15',
    author: 'VAT Faktura',
    keywords: ['ФОП w Polsce', 'założenie firmy dla Ukraińców', 'CEIDG', 'obcokrajowcy', 'przewodnik'],
    content: [
      '# Jak Założyć ФОП w Polsce - Przewodnik dla Ukraińców',
      '',
      'Jeśli przybyłeś z Ukrainy do Polski i chcesz założyć swoją firmę, ten artykuł pokazuje dokładnie, jak to zrobić krok po kroku.',
      '',
      '## Kim jest Ukrainiec w Polsce?',
      '',
      'Od 2022 roku wiele osób z Ukrainy przybyło do Polski i teraz pracuje tutaj legalnie. Jeśli jesteś tu dłużej niż turystycznie lub jako pracownik najemny, możesz założyć swoją własną firmę (ФОП).',
      '',
      '## Wymagane Dokumenty',
      '',
      'Jako Ukrainiec będziesz potrzebować:',
      '- **Paszport ukraiński** - dokument tożsamości',
      '- **PESEL** - numer uczestnika w Polsce (jeśli go nie masz, możesz go uzyskać)',
      '- **Dowód adresu** - potwierdzenie miejsca zamieszkania (umowa wynajmu, rachunek)',
      '- **Email i numer telefonu** - do komunikacji',
      '- **Kod PKD** - polska klasyfikacja działalności (co będziesz robić)',
      '',
      '## Jak Uzyskać PESEL?',
      '',
      'PESEL to osobisty numer identyfikacyjny w Polsce. Możesz go uzyskać w:',
      '- **UMiG** (Urząd Miasta/Gminy) w swoim mieście',
      '- **UdSC** (Urząd do spraw Cudzoziemców) - dla osób z Ukrainy',
      '',
      'Zwykle trwa to kilka dni. Będziesz potrzebować paszportu i dowodu adresu.',
      '',
      '## Процес Rejestracji - Krok po Kroku',
      '',
      '### Krok 1: Przygotuj Dokumenty',
      '',
      'Zbierz paszport, PESEL (lub numer tymczasowy), dowód adresu i określ, co będziesz robić (kod PKD).',
      '',
      '### Krok 2: Wybierz Kod PKD',
      '',
      'PKD to polska klasyfikacja działalności. Na przykład:',
      '- **62.01.Z** - Oprogramowanie (IT)',
      '- **82.11.Z** - Administracja biur (usługi adminitracyjne)',
      '- **78.20.Z** - Doradztwo w zakresie zasobów ludzkich',
      '- **85.59.Z** - Szkolenia (edukacja)',
      '',
      'Znajdziesz pełny katalog na stronie: https://pkd.stat.gov.pl',
      '',
      '### Krok 3: Zaloguj się na CEIDG',
      '',
      'Wejdź na stronę https://www.ceidg.gov.pl i zaloguj się:',
      '- Jeśli masz Profil Zaufany - użyj go',
      '- Jeśli masz e-dowód - możesz się zalogować elektronicznie',
      '- Jeśli nic nie masz - poproś o tymczasowy numer',
      '',
      '### Krok 4: Wypełnij Formularz JED',
      '',
      'Formularz JED to oficjalny dokument rejestracji. Wypełnisz:',
      '- Swoje imię i nazwisko (transliteracja z cyrylicy)',
      '- Adres siedziby (może być twój adres zamieszkania)',
      '- Kod PKD (typ działalności)',
      '- Numer telefonu i email',
      '',
      '### Krok 5: Podpisz Elektronicznie',
      '',
      'Musisz podpisać dokument elektronicznie (e-podpis). Możesz:',
      '- Użyć Profilu Zaufanego (Profil Zaufany)',
      '- Użyć e-dowodu',
      '- Poprosić o podpis papierowy w urzędzie',
      '',
      '### Krok 6: Otrzymaj NIP i Potwierdzenie',
      '',
      'Po 1-2 dniach otrzymasz:',
      '- **NIP** - numer identyfikacji podatkowej (np. 123-456-78-90)',
      '- **REGON** - rejestrowy numer organizacji',
      '- **Potwierdzenie rejestracji** - na emailu',
      '',
      '## Co Dalej? Kolejne Kroki',
      '',
      '### 1. Załóż Konto Bankowe',
      '',
      'Z NIP i dokumentami przejdź do polskiego banku (np. mBank, PKO BP, ING) i załóż konto biznesowe.',
      '',
      '### 2. Zarejestruj się w ZUS',
      '',
      'Po rejestracji w CEIDG musisz zgłosić się do ZUS (Zakład Ubezpieczeń Społecznych):',
      '- Będziesz płacić składki (około 250-400 PLN/miesiąc)',
      '- To ubezpieczenie społeczne',
      '',
      '### 3. Możesz Wystawiać Faktury',
      '',
      'Po kilku dniach możesz zacząć wystawiać faktury swoim klientom. VAT Faktura ułatwia to całkowicie bezpłatnie.',
      '',
      '## Podatki dla Ukraińców w Polsce',
      '',
      'Jeśli zarabiasz w Polsce, musisz płacić podatki:',
      '',
      '**PIT** (podatek dochodowy)',
      '- Stawka: 19% dla dochodów do ~120k PLN/rok',
      '- Składasz roczne zeznanie do 30 kwietnia',
      '',
      '**ZUS** (składki społeczne)',
      '- Około 250-400 PLN/miesiąc',
      '- Obowiązkowe dla każdej firmy',
      '',
      '**VAT** (jeśli applies)',
      '- Jeśli przychód > 200k PLN/rok, musisz się zarejestrować',
      '- VAT to 23% w Polsce (dla większości towarów/usług)',
      '',
      '## Wiza i Pobytu - Czy Mogę Pracować?',
      '',
      'Jako Ukrainiec możesz pracować w Polsce bez szczególnych zezwoleń, ale:',
      '',
      '- **Do 90 dni** - możesz być bez wizy (turysta/wolny ruch)',
      '- **Powyżej 90 dni** - powinieneś mieć zezwolenie na pobyt',
      '- **Praca jako przedsiębiorca** - może być zawoalowana forma pobytu',
      '',
      'Jeśli chcesz przedłużyć pobytu, możesz:',
      '1. Złożyć wniosek o zezwolenie na pobyt czasowy',
      '2. Zarejestrować się jako pracownik (umowa o pracę)',
      '3. Założyć firmę (ФОП) - to też może być powodem do przedłużenia',
      '',
      '## Czy to Warte Zachodu?',
      '',
      'Wiele Ukraińców założyło już firmy w Polsce i pracuje tutaj legalnie. Główne korzyści:',
      '',
      '- **Legalność** - wszystko jest przepisowo',
      '- **Dostęp do banku** - można zarabiać i transferować pieniądze',
      '- **Klient rozliczeniowy** - możesz pracować z polskimi i zagranicznymi firmami',
      '- **Przyszłość** - jeśli będziesz w Polsce dłużej',
      '',
      '## Potrzebujesz Pomocy?',
      '',
      'VAT Faktura już pomogła wielu Ukraińcom założyć firmy w Polsce. Możemy Ci pomóc na każdym etapie procesu rejestracji.',
    ].join('\n'),
  },
  {
    id: 'praca-bez-limitu',
    title: 'Jak Pracować Legalnie w Polsce - Przewodnik dla Obcokrajowców',
    slug: 'praca-bez-limitu-w-polsce',
    excerpt: 'Legalna praca w Polsce jako obcokrajowiec - umowa o pracę, kontakt, czy własna firma. Podatki, ubezpieczenie i bezpieczeństwo.',
    category: 'Dla obcokrajowców',
    readTime: '8 min',
    date: '2026-03-14',
    author: 'VAT Faktura',
    keywords: ['praca w Polsce', 'obcokrajowcy', 'legalna praca', 'umowa o pracę'],
    content: [
      '# Jak Pracować Legalnie w Polsce - Przewodnik dla Obcokrajowców',
      '',
      'Pracować w Polsce jako obcokrajowiec można legalnie i bezpiecznie. Ten artykuł wyjaśnia wszystkie opcje.',
      '',
      '## Opcje Pracy w Polsce',
      '',
      '### 1. Umowa o Pracę (Najemny)',
      '',
      'Najprostszy sposób - pracujesz dla firmy, ona Cię zatrudnia.',
      '- Umowa na czas określony lub nieokreślony',
      '- Pracodawca płaci podatki',
      '- Zawsze chroń się umową na piśmie',
      '',
      '### 2. Umowa o Dzieło (Kontrakt)',
      '',
      'Pracujesz na projekt, opłata za projekt/zadanie.',
      '- Nie musisz mieć firmy',
      '- Podatki płacisz sam (jeśli dochód > limit)',
      '- Elastyczne warunki',
      '',
      '### 3. Własna Firma (ФОП/Działalność)',
      '',
      'Pracujesz dla siebie - to to co opisujemy w VAT Faktura.',
      '- Pełna kontrola',
      '- Komplikacje: podatki, ZUS, sprawozdania',
      '- Ale większy potencjał zarobków',
      '',
      '## Bezpieczeństwo - Co Sprawdzić',
      '',
      '✓ Zawsze podpisuj umowę',
      '✓ Sprawdź firmę w KRS (https://www.krs-online.com.pl)',
      '✓ Nie płacić z góry za pracę',
      '✓ Miej kopię umowy',
      '✓ Zapytaj o ubezpieczenie NNW',
      '',
    ].join('\n'),
  },
]
