import { PIT_BLOG_POSTS } from './blog-posts-pit'
import { EXTRA_BLOG_POSTS } from './blog-posts-extra'
import { ZUS_BLOG_POSTS } from './blog-posts-zus'

export interface BlogPost {
  id: string
  title: string
  slug: string
  excerpt: string
  content: string
  category: string
  readTime: string
  date: string
  keywords: string[]
  author: string
  image?: string
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'ksef-guide',
    title: 'Kompletny Przewodnik po KSEF - Krajowym Systemie e-Faktur 2026',
    slug: 'kompletny-przewodnik-po-ksef',
    excerpt: 'Wszystko czego potrzebujesz wiedzieć o KSEF. Od rejestracji, przez wysyłanie, do obsługi błędów. Praktyczne wskazówki dla firm.',
    category: 'KSEF',
    readTime: '12 min',
    date: '2026-03-10',
    author: 'VAT Faktura',
    keywords: ['KSEF', 'e-faktury', 'krajowy system', 'faktury elektroniczne', 'poradnik KSEF'],
    content: [
      '# Kompletny Przewodnik po KSEF - Krajowym Systemie e-Faktur',
      '',
      'KSEF (Krajowy System e-Faktur) to obowi\u0105zkowy system przesy\u0142ania faktur elektronicznych dla firm VAT w Polsce. Od 1 lipca 2024 roku wszystkie faktury VAT musz\u0105 by\u0107 wysy\u0142ane do KSEF.',
      '',
      '## Co to jest KSEF?',
      '',
      'KSEF to centralne repozytorium wszystkich faktur VAT wystawianych w Polsce. System eliminuje potrzeb\u0119 przesy\u0142ania faktur bezpo\u015brednio odbiorcy.',
      '',
      '## Wymagania do korzystania z KSEF',
      '',
      '- Konto w Profilu Zaufanym lub e-Dowodem',
      '- NIP podlegaj\u0105cy opodatkowaniu VAT',
      '- Odpowiednie oprogramowanie (VAT Faktura wspiera KSEF w pe\u0142ni)',
      '',
      '## Jak si\u0119 zarejestrowa\u0107 w KSEF?',
      '',
      '1. Zaloguj si\u0119 do Profilu Zaufanego',
      '2. Przejd\u017a do sekcji KSEF',
      '3. Wype\u0142nij formularz rejestracyjny',
      '4. Poczekaj na potwierdzenie (24-48 godzin)',
      '5. Otrzymaj token dost\u0119pu API',
      '',
      '## Wysyłanie faktur do KSEF',
      '',
      'VAT Faktura automatycznie przesy\u0142a faktury do KSEF. Po wystawieniu faktury jest automatycznie przesy\u0142ana do systemu.',
      '',
      '## Najcz\u0119stsze b\u0142\u0119dy w KSEF',
      '',
      '- Niedope\u0142nione pola obowi\u0105zkowe na fakturze',
      '- B\u0142\u0119dne identyfikatory podatnika',
      '- Duplikaty faktur',
      '',
      '## Korzy\u015bci z KSEF',
      '',
      '- Automatyczne weryfikacje podatnika',
      '- Szybsze procedury kontrolne',
      '- Mo\u017cliwo\u015b\u0107 szybszego zwrotu VAT',
    ].join('\n'),
  },
  {
    id: 'vat-invoice',
    title: 'Jak Prawid\u0142owo Wystawi\u0107 Faktur\u0119 VAT - Praktyczny Poradnik 2026',
    slug: 'jak-prawidlowo-wystawic-fakture-vat',
    excerpt: 'Szczeg\u00f3\u0142owy poradnik dotycz\u0105cy wystawiania prawid\u0142owych faktur VAT. Poznaj wszystkie wymagane dane, zasady i b\u0142\u0119dy do unikni\u0119cia.',
    category: 'Faktury',
    readTime: '10 min',
    date: '2026-03-09',
    author: 'VAT Faktura',
    keywords: ['faktura VAT', 'wystawienie faktury', 'wymagane dane na fakturze', 'prawid\u0142owa faktura'],
    content: [
      '# Jak Prawid\u0142owo Wystawi\u0107 Faktur\u0119 VAT',
      '',
      'Prawid\u0142owe wystawienie faktury VAT jest kluczowe dla zgodno\u015bci z prawem i unikania problem\u00f3w z organami podatkowymi.',
      '',
      '## Wymagane dane na fakturze VAT',
      '',
      '- Numer faktury (unikatowy, sekwencyjny)',
      '- Data wystawienia',
      '- Dane sprzedawcy (imi\u0119/nazwa, NIP, adres)',
      '- Dane kupuj\u0105cego (imi\u0119/nazwa, NIP, adres)',
      '- Opis towaru/us\u0142ugi',
      '- Ilo\u015b\u0107 i jednostka',
      '- Cena jednostkowa netto',
      '- Stawka VAT (23%, 8%, 5%, 0%)',
      '- Kwota VAT',
      '- Kwota netto i brutto',
      '',
      '## R\u00f3\u017cne stawki VAT w Polsce',
      '',
      '- 23% - standardowa stawka (wi\u0119kszo\u015b\u0107 towar\u00f3w/us\u0142ug)',
      '- 8% - ni\u017csza stawka (artyku\u0142y spo\u017cywcze, leki, ksi\u0105\u017cki)',
      '- 5% - preferencyjna stawka (niekt\u00f3re us\u0142ugi)',
      '- 0% - zwolnione z VAT (eksport, us\u0142ugi finansowe)',
      '',
      '## Cz\u0119ste b\u0142\u0119dy na fakturach VAT',
      '',
      '1. **B\u0142\u0119dny NIP** - Zawsze weryfikuj NIP dostawcy/odbiorcy',
      '2. **Niew\u0142a\u015bciwa stawka VAT** - Sprawdzaj aktualne stawki',
      '3. **Niezgodno\u015b\u0107 danych** - Imiona/nazwiska/adresy',
      '',
      '## Terminy wystawienia i wys\u0142ania faktury',
      '',
      '- Faktura musi by\u0107 wystawiona do 15 dnia miesi\u0105ca nast\u0119pnego',
      '- Wysy\u0142ka do KSEF maksymalnie w ci\u0105gu 5 dni',
      '- VAT Faktura wy\u015bwietla wszystkie terminy',
    ].join('\n'),
  },
  {
    id: 'free-programs-comparison',
    title: 'Darmowe Programy do Fakturowania 2026 - Por\u00f3wnanie i Ranking',
    slug: 'darmowe-programy-do-fakturowania-porownanie',
    excerpt: 'Por\u00f3wnanie najlepszych darmowych program\u00f3w do fakturowania. KSEF, export PDF, limity, cechy. Kt\u00f3ra opcja jest najlepsza?',
    category: 'Por\u00f3wnanie',
    readTime: '14 min',
    date: '2026-03-08',
    author: 'VAT Faktura',
    keywords: ['darmowy program fakturowanie', 'najlepszy program faktura', 'por\u00f3wnanie fakturowania', 'bezp\u0142atne narz\u0119dzia VAT'],
    content: [
      '# Darmowe Programy do Fakturowania 2026 - Kompletne Por\u00f3wnanie',
      '',
      'W 2026 roku masz wiele opcji darmowych program\u00f3w do fakturowania. Porównujemy je wyczerpuj\u0105co.',
      '',
      '## VAT Faktura - Najlepsza opcja 100% bezp\u0142atna',
      '',
      '### Zalety',
      '- 100% bezp\u0142atny zawsze (bez limit\u00f3w)',
      '- Pe\u0142na integracja KSEF',
      '- Brak karty kredytowej',
      '- Unlimited faktury',
      '- Export PDF/KSEF',
      '',
      '## Por\u00f3wnanie z konkurencj\u0105',
      '',
      '### inFakt',
      '- Darmowy do 10 faktur/miesi\u0105c',
      '- Potem p\u0142atny abonament',
      '- KSEF wspierany',
      '',
      '### Podsumowanie: VAT Faktura wygrywa',
      '',
      'VAT Faktura jest jedynym w pe\u0142ni darmowym programem bez \u017cadnych limit\u00f3w.',
    ].join('\n'),
  },
  {
    id: 'freelancer-guide',
    title: 'Fakturowanie dla Freelancer\u00f3w - Praktyczny Poradnik Podatki i KSEF',
    slug: 'fakturowanie-dla-freelancerow-praktyczny-poradnik',
    excerpt: 'Jak prawid\u0142owo fakturowa\u0107 jako freelancer. Podatki, NIP, KSEF, limity przychod\u00f3w. Wszystko co musisz wiedzieć.',
    category: 'Freelancerzy',
    readTime: '11 min',
    date: '2026-03-07',
    author: 'VAT Faktura',
    keywords: ['fakturowanie freelancer', 'JDG faktura', 'podatki freelancer', 'KSEF dla freelancer\u00f3w'],
    content: [
      '# Fakturowanie dla Freelancer\u00f3w - Praktyczny Poradnik',
      '',
      'Jako freelancer mo\u017cesz fakturowa\u0107 na kilka sposob\u00f3w. Poznaj r\u00f3\u017cne opcje, podatki i wymagania KSEF.',
      '',
      '## Formy prowadzenia dzia\u0142alno\u015bci freelancera',
      '',
      '### 1. Jednoosobowa Dzia\u0142alno\u015b\u0107 Gospodarcza (JDG)',
      '- Najpopularniejsza forma',
      '- Wymaga rejestracji w CEIDG',
      '- Mo\u017cliwo\u015b\u0107 ryczałtu (8.5% lub 14%)',
      '',
      '### 2. Dzia\u0142alno\u015b\u0107 bez rejestracji',
      '- Do 50 000 PLN przychodu rocznie',
      '- Podatek dochodowy standardowo',
      '',
      '### 3. Vat-owiec',
      '- Pe\u0142na kwota VAT do rozliczania',
      '- Tylko powy\u017cej 200 000 PLN przychodu',
      '- Obowi\u0105zkowy KSEF',
      '',
      '## Limity przychod\u00f3w dla freelancer\u00f3w',
      '',
      '- Do 50 000 PLN - brak KSEF',
      '- 50 000-200 000 PLN - VAT-owiec bez KSEF',
      '- Powy\u017cej 200 000 PLN - obowi\u0105zkowy VAT i KSEF',
      '',
      '## Podatki dla freelancer\u00f3w',
      '',
      '- Ryczałt 8.5% - najkorzystniejszy',
      '- Podatek dochodowy 18% lub 32%',
      '- ZUS - 20% przychodu dla pracuj\u0105cych za siebie',
    ].join('\n'),
  },
  {
    id: 'business-system',
    title: 'System Fakturowania dla Ma\u0142ych Firm - Kompleksowy Przewodnik',
    slug: 'system-fakturowania-dla-malych-firm',
    excerpt: 'Jak wybudowa\u0107 efektywny system fakturowania w ma\u0142ej firmie. Procesy, narz\u0119dzia, KSEF i integracje dla maksymalnej wydajno\u015bci.',
    category: 'Biznes',
    readTime: '13 min',
    date: '2026-03-06',
    author: 'VAT Faktura',
    keywords: ['system fakturowania', 'fakturowanie firmy', 'zarz\u0105dzanie fakturami', 'procesy fakturowania'],
    content: [
      '# System Fakturowania dla Ma\u0142ych Firm - Kompleksowy Przewodnik',
      '',
      'Prawid\u0142owy system fakturowania to kluczowy element efektywno\u015bci ma\u0142ej firmy.',
      '',
      '## Elementy dobrego systemu fakturowania',
      '',
      '### 1. Szablon faktury',
      '- Sp\u00f3jny branding',
      '- Wszystkie wymagane dane',
      '- \u0141atwy do modyfikacji',
      '',
      '### 2. Numeracja i archiwizacja',
      '- Sekwencyjna numeracja',
      '- Jasne archiwa (papierowe lub elektroniczne)',
      '- Dost\u0119p dla os\u00f3b upowa\u017cnionych',
      '',
      '### 3. Przesy\u0142ka i tracking',
      '- KSEF dla firm VAT-ownik\u00f3w',
      '- Email do odbiorcy',
      '- Tracking statusu p\u0142atno\u015bci',
      '',
      '### 4. Archiwizacja dokument\u00f3w',
      '- Obowi\u0105zkowe 5 lat',
      '- Bezpieczne przechowywanie',
      '- \u0141atwy dost\u0119p dla kontroli',
      '',
      '## Integracje VAT Faktura dla firm',
      '',
      '- Automatyczne przesy\u0142ki do KSEF',
      '- Export do Excel/PDF',
      '- Kalkulacja VAT',
      '- Raporty i statystyki',
      '',
      '## Efektywno\u015b\u0107 i oszcz\u0119dno\u015bci czasu',
      '',
      'Prawid\u0142owy system zmniejsza czas na fakturowanie z 30 minut do 5 minut per faktura. To oszcz\u0119dno\u015bci 50+ godzin rocznie dla ma\u0142ej firmy!',
    ].join('\n'),
  },
]

const ALL_POSTS: BlogPost[] = [...BLOG_POSTS, ...PIT_BLOG_POSTS, ...EXTRA_BLOG_POSTS, ...ZUS_BLOG_POSTS]

export function getBlogPost(slug: string): BlogPost | undefined {
  return ALL_POSTS.find(post => post.slug === slug)
}

export function getAllBlogPosts(): BlogPost[] {
  return ALL_POSTS.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
}
